In [336]:
## Impact richesse département

In [337]:
# importation des packages
import os 
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import statsmodels.api as sm

In [338]:
# Mes modèles, avec des F-tests différents

path_VAR_CTRL = r'D:/Données/ENSAE/2A/Stat_App/Variables_controle.csv'
VAR_CTRL=pd.read_csv(path_VAR_CTRL ,sep=',')
path_VAR_EXPL_CAT = r'D:/Données/ENSAE/2A/Stat_App/VAR_EXPL_CAT.csv'
VAR_EXPL_CAT=pd.read_csv(path_VAR_EXPL_CAT ,sep=',')

# Première analyse sur l'effet du revenu fiscal moyen sur les points ISA

In [339]:
VAR_EXPL_CAT_1 = VAR_EXPL_CAT[['Numero_finess', 'Personnel médical','stjr',
       'Personnels de direction et administratifs',
       'Personnels des services de soins', 'Personnels éducatifs et sociaux',
       'Personnels médico-techniques', 'Personnels techniques et ouvriers',
        'Internes']]
VAR_EXPL_CAT_1= VAR_EXPL_CAT_1.fillna(0)

In [340]:
VAR_EXPL_CAT_1

,Numero_finess,Personnel médical,stjr,Personnels de direction et administratifs,Personnels des services de soins,Personnels éducatifs et sociaux,Personnels médico-techniques,Personnels techniques et ouvriers,Internes
0,010007300,7.500,2,2.250000,4.200000,0.000000,0.000000,0.000,0.00
1,010008407,32.820,1,21.196667,97.323333,0.846667,9.206667,26.440,0.00
2,010009132,1.865,1,4.175000,46.700000,1.065000,1.130000,13.465,0.00
3,010780054,152.630,1,118.605000,388.590000,4.930000,107.660000,112.630,195.09
4,010780062,29.550,1,58.450000,336.540000,5.450000,29.320000,57.570,6.45
...,...,...,...,...,...,...,...,...,...
1147,950300277,52.560,2,74.950000,246.990000,1.100000,6.460000,14.460,0.00
1148,950300301,11.270,2,22.560000,103.560000,1.380000,2.940000,3.000,0.00
1149,950300350,13.800,2,6.600000,27.550000,0.000000,3.000000,1.000,0.00
1150,950630012,13.800,3,23.070000,177.880000,39.070000,5.330000,12.700,2.49
1151,950807982,75.800,2,61.000000,288.230000,1.130000,7.690000,6.000,0.00

In [341]:
VAR_EXPL_CAT_1 = VAR_EXPL_CAT_1.apply(lambda x: np.log(x) if x.name in ['Personnel médical',
       'Personnels de direction et administratifs',
       'Personnels des services de soins', 'Personnels éducatifs et sociaux',
       'Personnels médico-techniques', 'Personnels techniques et ouvriers',
        'Internes'] else x)

#On remplace les valeurs -infini apparues après l'application du log par la valeur -3 c'est-à-dire log(0.001)
from numpy import inf
VAR_EXPL_CAT_1 = VAR_EXPL_CAT_1.replace(-inf, -3)

VAR_EXPL_CAT_1

C:\Users\Vinciane\Anaconda3\lib\site-packages\pandas\core\arraylike.py:358: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

,Numero_finess,Personnel médical,stjr,Personnels de direction et administratifs,Personnels des services de soins,Personnels éducatifs et sociaux,Personnels médico-techniques,Personnels techniques et ouvriers,Internes
0,010007300,2.014903,2,0.810930,1.435085,-3.000000,-3.000000,-3.000000,-3.000000
1,010008407,3.491038,1,3.053844,4.578039,-0.166448,2.219928,3.274878,-3.000000
2,010009132,0.623261,1,1.429114,3.843744,0.062975,0.122218,2.600094,-3.000000
3,010780054,5.028017,1,4.775799,5.962525,1.595339,4.678978,4.724108,5.273461
4,010780062,3.386084,1,4.068172,5.818717,1.695616,3.378270,4.053002,1.864080
...,...,...,...,...,...,...,...,...,...
1147,950300277,3.961955,2,4.316821,5.509348,0.095310,1.865629,2.671386,-3.000000
1148,950300301,2.422144,2,3.116178,4.640151,0.322083,1.078410,1.098612,-3.000000
1149,950300350,2.624669,2,1.887070,3.316003,-3.000000,1.098612,0.000000,-3.000000
1150,950630012,2.624669,3,3.138533,5.181109,3.665355,1.673351,2.541602,0.912283
1151,950807982,4.328098,2,4.110874,5.663759,0.122218,2.039921,1.791759,-3.000000

In [342]:
stjr_1= VAR_EXPL_CAT_1.copy()

In [343]:
VAR_CTRL.columns
#Je prends Cpaital_LIT_MCO et Capital_Bloc

Index(['Numero_finess', 'Points_ISA', 'stjr', 'dep', 'Departement', 'COMINSEE',
       'Capital_Lit_MCO', 'Capital_Bloc', 'Capital_imagerie',
       'Capital_Examens_biologiques', 'Capital_telemed', 'SEJHC_MED',
       'SEJHC_CHI', 'SEJHC_OBS', 'SEJHC_MCO', 'Taux_chomage_par_dep',
       'Population', 'Dep Moyenne Salaires Horaires',
       'Dep Moyenne Salaires Cadre Horaires',
       'Dep Moyenne Salaires Prof Intermédiaire Horaires',
       'Dep Moyenne Salaires Employé Horaires',
       'Moyenne Revenus Fiscaux Départementaux', 'Bloc_politique'],
      dtype='object')

In [344]:
VAR_CTRL = VAR_CTRL.apply(lambda x: np.log(x) if x.name in ['Points_ISA', 'Capital_Lit_MCO', 'Capital_Bloc', 'Capital_imagerie',
       'Capital_Examens_biologiques', 'Capital_telemed', 'Population'] else x)

#On remplace les valeurs -infini apparues après l'application du log par la valeur -3 c'est-à-dire log(0.001)
from numpy import inf
VAR_CTRL = VAR_CTRL.replace(-inf, -3)

VAR_CTRL

C:\Users\Vinciane\Anaconda3\lib\site-packages\pandas\core\arraylike.py:358: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

,Numero_finess,Points_ISA,stjr,dep,Departement,COMINSEE,Capital_Lit_MCO,Capital_Bloc,Capital_imagerie,Capital_Examens_biologiques,...,SEJHC_OBS,SEJHC_MCO,Taux_chomage_par_dep,Population,Dep Moyenne Salaires Horaires,Dep Moyenne Salaires Cadre Horaires,Dep Moyenne Salaires Prof Intermédiaire Horaires,Dep Moyenne Salaires Employé Horaires,Moyenne Revenus Fiscaux Départementaux,Bloc_politique
0,060000528,12.785189,3,06,Alpes-Maritimes,06088,4.852030,2.079442,2.197225,6.812345,...,0.0,7020.0,8.9,12.745844,12.579245,22.518868,12.864151,8.835849,12288.0,Centre droit à droite
1,060780947,12.069981,3,06,Alpes-Maritimes,06088,4.653960,1.609438,1.386294,-3.000000,...,0.0,9754.0,8.9,12.745844,12.579245,22.518868,12.864151,8.835849,12288.0,Centre droit à droite
2,060791811,11.894321,3,06,Alpes-Maritimes,06088,4.510860,0.693147,0.693147,-3.000000,...,0.0,2558.0,8.9,12.745844,12.579245,22.518868,12.864151,8.835849,12288.0,Centre droit à droite
3,060780442,10.036373,2,06,Alpes-Maritimes,06088,3.401197,1.791759,0.000000,-3.000000,...,0.0,1605.0,8.9,12.745844,12.579245,22.518868,12.864151,8.835849,12288.0,Centre droit à droite
4,060780715,12.742716,2,06,Alpes-Maritimes,06088,5.545177,3.258097,2.302585,-3.000000,...,1467.0,15866.0,8.9,12.745844,12.579245,22.518868,12.864151,8.835849,12288.0,Centre droit à droite
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1155,120780085,10.729103,1,12,Aveyron,12089,3.526361,1.609438,1.098612,12.367630,...,0.0,2056.0,6.4,8.822764,10.115789,20.252632,11.963158,8.478947,9936.0,Extrême gauche à gauche
1156,480780097,12.391985,1,48,Lozère,48095,4.204693,1.791759,1.791759,12.956158,...,392.0,3599.5,5.3,9.375177,10.075000,20.475000,11.775000,8.600000,8555.0,Centre gauche à centre droit
1157,480780162,8.648072,1,48,Lozère,48080,3.135494,-3.000000,0.000000,-3.000000,...,0.0,421.0,5.3,8.038189,10.075000,20.475000,11.775000,8.600000,8555.0,Centre gauche à centre droit
1158,480780121,7.781744,1,48,Lozère,48140,3.091042,-3.000000,-3.000000,-3.000000,...,0.0,205.0,5.3,8.370779,10.075000,20.475000,11.775000,8.600000,8555.0,Centre droit à droite
1159,480780154,6.249357,1,48,Lozère,48092,2.995732,-3.000000,-3.000000,-3.000000,...,0.0,384.0,5.3,8.613230,10.075000,20.475000,11.775000,8.600000,8555.0,Centre droit à droite

In [345]:
VAR_CTRL

,Numero_finess,Points_ISA,stjr,dep,Departement,COMINSEE,Capital_Lit_MCO,Capital_Bloc,Capital_imagerie,Capital_Examens_biologiques,...,SEJHC_OBS,SEJHC_MCO,Taux_chomage_par_dep,Population,Dep Moyenne Salaires Horaires,Dep Moyenne Salaires Cadre Horaires,Dep Moyenne Salaires Prof Intermédiaire Horaires,Dep Moyenne Salaires Employé Horaires,Moyenne Revenus Fiscaux Départementaux,Bloc_politique
0,060000528,12.785189,3,06,Alpes-Maritimes,06088,4.852030,2.079442,2.197225,6.812345,...,0.0,7020.0,8.9,12.745844,12.579245,22.518868,12.864151,8.835849,12288.0,Centre droit à droite
1,060780947,12.069981,3,06,Alpes-Maritimes,06088,4.653960,1.609438,1.386294,-3.000000,...,0.0,9754.0,8.9,12.745844,12.579245,22.518868,12.864151,8.835849,12288.0,Centre droit à droite
2,060791811,11.894321,3,06,Alpes-Maritimes,06088,4.510860,0.693147,0.693147,-3.000000,...,0.0,2558.0,8.9,12.745844,12.579245,22.518868,12.864151,8.835849,12288.0,Centre droit à droite
3,060780442,10.036373,2,06,Alpes-Maritimes,06088,3.401197,1.791759,0.000000,-3.000000,...,0.0,1605.0,8.9,12.745844,12.579245,22.518868,12.864151,8.835849,12288.0,Centre droit à droite
4,060780715,12.742716,2,06,Alpes-Maritimes,06088,5.545177,3.258097,2.302585,-3.000000,...,1467.0,15866.0,8.9,12.745844,12.579245,22.518868,12.864151,8.835849,12288.0,Centre droit à droite
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1155,120780085,10.729103,1,12,Aveyron,12089,3.526361,1.609438,1.098612,12.367630,...,0.0,2056.0,6.4,8.822764,10.115789,20.252632,11.963158,8.478947,9936.0,Extrême gauche à gauche
1156,480780097,12.391985,1,48,Lozère,48095,4.204693,1.791759,1.791759,12.956158,...,392.0,3599.5,5.3,9.375177,10.075000,20.475000,11.775000,8.600000,8555.0,Centre gauche à centre droit
1157,480780162,8.648072,1,48,Lozère,48080,3.135494,-3.000000,0.000000,-3.000000,...,0.0,421.0,5.3,8.038189,10.075000,20.475000,11.775000,8.600000,8555.0,Centre gauche à centre droit
1158,480780121,7.781744,1,48,Lozère,48140,3.091042,-3.000000,-3.000000,-3.000000,...,0.0,205.0,5.3,8.370779,10.075000,20.475000,11.775000,8.600000,8555.0,Centre droit à droite
1159,480780154,6.249357,1,48,Lozère,48092,2.995732,-3.000000,-3.000000,-3.000000,...,0.0,384.0,5.3,8.613230,10.075000,20.475000,11.775000,8.600000,8555.0,Centre droit à droite

In [346]:
VAR_CTRL.describe()

,Points_ISA,stjr,Capital_Lit_MCO,Capital_Bloc,Capital_imagerie,Capital_Examens_biologiques,Capital_telemed,SEJHC_MED,SEJHC_CHI,SEJHC_OBS,SEJHC_MCO,Taux_chomage_par_dep,Population,Dep Moyenne Salaires Horaires,Dep Moyenne Salaires Cadre Horaires,Dep Moyenne Salaires Prof Intermédiaire Horaires,Dep Moyenne Salaires Employé Horaires,Moyenne Revenus Fiscaux Départementaux
count,1160.000000,1160.000000,1137.000000,1150.000000,1160.000000,1147.000000,1160.000000,1160.000000,1160.000000,1159.000000,1160.000000,1160.000000,1160.000000,1160.000000,1160.000000,1160.000000,1160.000000,1160.000000
mean,11.353144,1.706897,4.226901,0.807590,-0.006461,1.250664,-1.976544,3952.631964,2094.817960,673.190511,6720.060098,8.291121,10.163531,11.795883,21.766274,12.675999,8.784310,10649.390517
std,1.753422,0.716106,1.418402,2.260586,2.280211,7.168320,1.715649,5174.050854,2472.139334,1147.577563,7604.160425,1.662088,1.667519,1.909655,1.674863,0.522909,0.353789,2065.446677
min,4.903718,1.000000,-3.000000,-3.000000,-3.000000,-3.000000,-3.000000,0.000000,0.000000,0.000000,0.000000,5.000000,5.204007,9.862500,19.750000,11.740000,8.261905,6282.000000
25%,10.307845,1.000000,3.555348,0.000000,-3.000000,-3.000000,-3.000000,366.250000,0.000000,0.000000,1205.500000,7.000000,8.994079,10.633333,20.775000,12.357075,8.555172,9471.000000
50%,11.529000,2.000000,4.442651,1.791759,1.098612,-3.000000,-3.000000,1963.000000,1430.500000,0.000000,4168.500000,8.000000,10.041291,11.204762,21.280808,12.535714,8.700862,10239.000000
75%,12.607883,2.000000,5.143611,2.374068,1.945910,10.922160,0.000000,5563.750000,3176.250000,1080.875000,9741.250000,9.300000,11.039284,11.981429,22.083750,12.902500,8.848113,11536.000000
max,16.025641,3.000000,6.961296,4.060443,3.332205,16.176472,2.397895,39884.000000,20991.000000,7639.000000,60719.000000,13.800000,14.569683,17.800000,27.600000,14.185000,9.742553,16895.000000

Le premier quartile des revenus fiscaux moyens par mois est à 9471, et le troisième quartile à 11536. On sépare en deux bases : celles avec les départements avec les plus faibles revenus, et celles avec les départements avec les plus hauts revenus.

In [347]:
# Les établissements avec des revenus départements  trés élevés

VAR_CTRL_ELEVES = VAR_CTRL.copy()
VAR_CTRL_ELEVES= VAR_CTRL_ELEVES.rename(columns = {'Moyenne Revenus Fiscaux Départementaux': 'Rev_dep'})

VAR_CTRL_ELEVES= VAR_CTRL_ELEVES[VAR_CTRL_ELEVES.Rev_dep >= 11536]

In [348]:
# Les établissements avec des revenus départements trésfaibles

VAR_CTRL_FAIBLES = VAR_CTRL.copy()
VAR_CTRL_FAIBLES = VAR_CTRL_FAIBLES.rename(columns = {'Moyenne Revenus Fiscaux Départementaux': 'Rev_dep'})

VAR_CTRL_FAIBLES = VAR_CTRL_FAIBLES[VAR_CTRL_FAIBLES.Rev_dep <= 9471]

In [349]:
VAR_CTRL_FAIBLES

,Numero_finess,Points_ISA,stjr,dep,Departement,COMINSEE,Capital_Lit_MCO,Capital_Bloc,Capital_imagerie,Capital_Examens_biologiques,...,SEJHC_OBS,SEJHC_MCO,Taux_chomage_par_dep,Population,Dep Moyenne Salaires Horaires,Dep Moyenne Salaires Cadre Horaires,Dep Moyenne Salaires Prof Intermédiaire Horaires,Dep Moyenne Salaires Employé Horaires,Rev_dep,Bloc_politique
89,350002812,11.019027,3,35,Ille-et-Vilaine,35238,3.988984,1.386294,2.197225,11.852429,...,0.00,2609.00,6.4,12.236573,11.434091,20.478409,12.553409,8.819318,9401.0,Centre gauche à centre droit
90,350002192,12.499743,3,35,Ille-et-Vilaine,35238,5.267858,2.397895,1.386294,-3.000000,...,0.00,10701.00,6.4,12.236573,11.434091,20.478409,12.553409,8.819318,9401.0,Centre gauche à centre droit
91,350002200,9.658084,3,35,Ille-et-Vilaine,35238,1.945910,-3.000000,0.000000,-3.000000,...,0.00,276.00,6.4,12.236573,11.434091,20.478409,12.553409,8.819318,9401.0,Centre gauche à centre droit
92,350000139,12.581770,3,35,Ille-et-Vilaine,35238,4.962845,2.708050,-3.000000,-3.000000,...,4960.00,9592.00,6.4,12.236573,11.434091,20.478409,12.553409,8.819318,9401.0,Centre gauche à centre droit
93,350005179,15.037342,1,35,Ille-et-Vilaine,35238,5.771441,3.871201,2.564949,14.424276,...,1461.75,17740.75,6.4,12.236573,11.434091,20.478409,12.553409,8.819318,9401.0,Centre gauche à centre droit
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1113,240000109,8.536630,1,24,Dordogne,24311,1.386294,-3.000000,-3.000000,-3.000000,...,0.00,142.00,8.7,8.159947,10.264516,20.806452,12.219355,8.580645,7819.0,Centre gauche à centre droit
1156,480780097,12.391985,1,48,Lozère,48095,4.204693,1.791759,1.791759,12.956158,...,392.00,3599.50,5.3,9.375177,10.075000,20.475000,11.775000,8.600000,8555.0,Centre gauche à centre droit
1157,480780162,8.648072,1,48,Lozère,48080,3.135494,-3.000000,0.000000,-3.000000,...,0.00,421.00,5.3,8.038189,10.075000,20.475000,11.775000,8.600000,8555.0,Centre gauche à centre droit
1158,480780121,7.781744,1,48,Lozère,48140,3.091042,-3.000000,-3.000000,-3.000000,...,0.00,205.00,5.3,8.370779,10.075000,20.475000,11.775000,8.600000,8555.0,Centre droit à droite
1159,480780154,6.249357,1,48,Lozère,48092,2.995732,-3.000000,-3.000000,-3.000000,...,0.00,384.00,5.3,8.613230,10.075000,20.475000,11.775000,8.600000,8555.0,Centre droit à droite

In [350]:
VAR_CTRL_FAIBLES= VAR_CTRL_FAIBLES.fillna(0)
VAR_CTRL_ELEVES= VAR_CTRL_ELEVES.fillna(0)
#stjr_1 = stjr_1.fillna(0)

In [352]:
analyse_dep_faibles = pd.merge(VAR_CTRL_FAIBLES, VAR_EXPL_CAT_1)

analyse_dep_eleves = pd.merge(VAR_CTRL_ELEVES, VAR_EXPL_CAT_1)

In [353]:
analyse_dep_faibles.columns

Index(['Numero_finess', 'Points_ISA', 'stjr', 'dep', 'Departement', 'COMINSEE',
       'Capital_Lit_MCO', 'Capital_Bloc', 'Capital_imagerie',
       'Capital_Examens_biologiques', 'Capital_telemed', 'SEJHC_MED',
       'SEJHC_CHI', 'SEJHC_OBS', 'SEJHC_MCO', 'Taux_chomage_par_dep',
       'Population', 'Dep Moyenne Salaires Horaires',
       'Dep Moyenne Salaires Cadre Horaires',
       'Dep Moyenne Salaires Prof Intermédiaire Horaires',
       'Dep Moyenne Salaires Employé Horaires', 'Rev_dep', 'Bloc_politique',
       'Personnel médical', 'Personnels de direction et administratifs',
       'Personnels des services de soins', 'Personnels éducatifs et sociaux',
       'Personnels médico-techniques', 'Personnels techniques et ouvriers',
       'Internes'],
      dtype='object')

In [354]:
analyse_dep_faibles_X =analyse_dep_faibles[["Personnel médical","Internes",'Personnels de direction et administratifs',
       'Personnels des services de soins', 'Personnels éducatifs et sociaux',
       'Personnels médico-techniques', 'Personnels techniques et ouvriers', 
        'Capital_Lit_MCO', 'Capital_Bloc', 'Capital_imagerie', 'Population',
       'Capital_Examens_biologiques', 'Capital_telemed']]
analyse_dep_faibles_Y =analyse_dep_faibles[['Points_ISA']]
analyse_dep_eleves_X =analyse_dep_eleves[["Personnel médical","Internes",'Personnels de direction et administratifs',
       'Personnels des services de soins', 'Personnels éducatifs et sociaux',
       'Personnels médico-techniques', 'Personnels techniques et ouvriers', 
       'Capital_Lit_MCO', 'Capital_Bloc', 'Capital_imagerie', 'Population',
       'Capital_Examens_biologiques', 'Capital_telemed']]
analyse_dep_eleves_Y =analyse_dep_eleves[['Points_ISA']]

In [355]:
analyse_dep_faibles_X

,Personnel médical,Internes,Personnels de direction et administratifs,Personnels des services de soins,Personnels éducatifs et sociaux,Personnels médico-techniques,Personnels techniques et ouvriers,Capital_Lit_MCO,Capital_Bloc,Capital_imagerie,Population,Capital_Examens_biologiques,Capital_telemed
0,3.952397,4.276666,4.582413,4.983675,0.940007,4.844108,2.928524,3.988984,1.386294,2.197225,12.236573,11.852429,0.693147
1,4.233962,3.044522,4.114964,5.989187,1.690096,2.513656,3.492560,5.267858,2.397895,1.386294,12.236573,-3.000000,1.098612
2,2.634045,1.118415,3.226447,5.057010,-0.030459,1.244155,3.179719,1.945910,-3.000000,0.000000,12.236573,-3.000000,0.693147
3,3.990834,2.890372,4.515245,5.911907,-1.203973,2.710713,-3.000000,4.962845,2.708050,-3.000000,12.236573,-3.000000,-3.000000
4,5.745977,6.449751,5.208488,6.965833,2.323123,5.046924,5.604929,5.771441,3.871201,2.564949,12.236573,14.424276,1.098612
...,...,...,...,...,...,...,...,...,...,...,...,...,...
293,0.955511,-3.000000,2.272126,3.865770,-0.287682,-0.223144,3.148882,1.386294,-3.000000,-3.000000,8.159947,-3.000000,-3.000000
294,4.069283,2.890372,3.539993,4.997888,1.483875,2.924236,3.096256,4.204693,1.791759,1.791759,9.375177,12.956158,0.000000
295,1.360977,-3.000000,1.945910,3.837299,0.000000,0.000000,2.420368,3.135494,-3.000000,0.000000,8.038189,-3.000000,1.945910
296,1.909543,-3.000000,0.565314,3.149311,-3.000000,-1.386294,1.324419,3.091042,-3.000000,-3.000000,8.370779,-3.000000,-3.000000
297,1.388791,-3.000000,1.249902,3.651697,-1.714798,-3.000000,1.916923,2.995732,-3.000000,-3.000000,8.613230,-3.000000,-3.000000

In [356]:
analyse_dep_faibles_X = sm.add_constant(analyse_dep_faibles_X) # on ajoute une constante, sinon la régression se fait sans, par défaut
y = analyse_dep_faibles[['Points_ISA']]

model_dep_faibles = sm.OLS(y, analyse_dep_faibles_X)
results_dep_faibles = model_dep_faibles.fit()
print(results_dep_faibles.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:             Points_ISA   R-squared:                       0.892
Model:                            OLS   Adj. R-squared:                  0.887
Method:                 Least Squares   F-statistic:                     180.7
Date:                Thu, 13 May 2021   Prob (F-statistic):          6.65e-129
Time:                        15:33:51   Log-Likelihood:                -265.24
No. Observations:                 298   AIC:                             558.5
Df Residuals:                     284   BIC:                             610.2
Df Model:                          13
Covariance Type:            nonrobust
=============================================================================================================
                                                coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------------------------------
const                                         7.6672      0.426     18.015      0.000       6.830       8.505
Personnel médical                             0.2423      0.048      5.070      0.000       0.148       0.336
Internes                                      0.0877      0.020      4.388      0.000       0.048       0.127
Personnels de direction et administratifs    -0.0725      0.082     -0.885      0.377      -0.234       0.089
Personnels des services de soins              0.3875      0.112      3.445      0.001       0.166       0.609
Personnels éducatifs et sociaux              -0.0120      0.036     -0.331      0.741      -0.084       0.059
Personnels médico-techniques                  0.1024      0.034      3.031      0.003       0.036       0.169
Personnels techniques et ouvriers            -0.1045      0.036     -2.936      0.004      -0.175      -0.034
Capital_Lit_MCO                               0.3171      0.056      5.676      0.000       0.207       0.427
Capital_Bloc                                  0.2025      0.028      7.157      0.000       0.147       0.258
Capital_imagerie                              0.0012      0.021      0.058      0.954      -0.040       0.043
Population                                   -0.0263      0.030     -0.867      0.387      -0.086       0.033
Capital_Examens_biologiques                   0.0173      0.008      2.283      0.023       0.002       0.032
Capital_telemed                               0.0037      0.023      0.161      0.872      -0.042       0.049
==============================================================================
Omnibus:                      107.683   Durbin-Watson:                   1.773
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              720.283
Skew:                          -1.303   Prob(JB):                    3.91e-157
Kurtosis:                      10.157   Cond. No.                         172.
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [357]:
analyse_dep_eleves_X = sm.add_constant(analyse_dep_eleves_X) # on ajoute une constante, sinon la régression se fait sans, par défaut
y = analyse_dep_eleves[['Points_ISA']]

model_dep_eleves = sm.OLS(y, analyse_dep_eleves_X)
results_dep_eleves = model_dep_eleves.fit()
print(results_dep_eleves.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:             Points_ISA   R-squared:                       0.852
Model:                            OLS   Adj. R-squared:                  0.845
Method:                 Least Squares   F-statistic:                     120.7
Date:                Thu, 13 May 2021   Prob (F-statistic):          6.09e-105
Time:                        15:33:51   Log-Likelihood:                -283.16
No. Observations:                 287   AIC:                             594.3
Df Residuals:                     273   BIC:                             645.6
Df Model:                          13
Covariance Type:            nonrobust
=============================================================================================================
                                                coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------------------------------
const                                         9.7501      0.358     27.201      0.000       9.044      10.456
Personnel médical                             0.0318      0.048      0.666      0.506      -0.062       0.126
Internes                                      0.0753      0.020      3.721      0.000       0.035       0.115
Personnels de direction et administratifs    -0.0114      0.081     -0.140      0.889      -0.171       0.148
Personnels des services de soins              0.1348      0.091      1.484      0.139      -0.044       0.314
Personnels éducatifs et sociaux              -0.0406      0.033     -1.227      0.221      -0.106       0.025
Personnels médico-techniques                  0.0957      0.036      2.627      0.009       0.024       0.167
Personnels techniques et ouvriers             0.0162      0.052      0.312      0.755      -0.086       0.118
Capital_Lit_MCO                               0.2619      0.052      5.045      0.000       0.160       0.364
Capital_Bloc                                  0.3032      0.029     10.519      0.000       0.246       0.360
Capital_imagerie                              0.0742      0.023      3.235      0.001       0.029       0.119
Population                                   -0.0564      0.022     -2.609      0.010      -0.099      -0.014
Capital_Examens_biologiques                   0.0281      0.009      3.296      0.001       0.011       0.045
Capital_telemed                               0.0715      0.027      2.681      0.008       0.019       0.124
==============================================================================
Omnibus:                       25.142   Durbin-Watson:                   2.008
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               63.887
Skew:                           0.377   Prob(JB):                     1.34e-14
Kurtosis:                       5.185   Cond. No.                         135.
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [358]:
# Deuxième analyse : effet de la moyenne des salaires des intermédaires (infirmières) sur leur employabilité

In [359]:
VAR_EXPL_CAT

,Unnamed: 0,Numero_finess,Médecins libéraux,Autres personnels médicaux libéraux,Médecins salariés,Autres personnels médicaux salariés,Personnels de direction et administratifs,Personnels des services de soins,Personnels éducatifs et sociaux,Personnels médico-techniques,Personnels techniques et ouvriers,Points_ISA,stjr,Internes,Personnel médical,Personnel médical si LIB=0.1,Personnel médical si LIB=0.9
0,0,010007300,4.5,3.0,0.000,0.00,2.250000,4.200000,NaN,NaN,NaN,3785.960000,2,0.00,7.500,1.500,13.500
1,1,010008407,0.0,0.0,18.490,14.33,21.196667,97.323333,0.846667,9.206667,26.440,165054.798333,1,0.00,32.820,32.820,32.820
2,2,010009132,0.0,0.0,1.795,0.07,4.175000,46.700000,1.065000,1.130000,13.465,5715.170000,1,0.00,1.865,1.865,1.865
3,3,010780054,4.5,1.0,102.600,44.53,118.605000,388.590000,4.930000,107.660000,112.630,787929.068333,1,195.09,152.630,148.230,157.030
4,4,010780062,0.0,0.0,19.450,10.10,58.450000,336.540000,5.450000,29.320000,57.570,188174.950000,1,6.45,29.550,29.550,29.550
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1147,1147,950300277,29.5,16.0,4.060,3.00,74.950000,246.990000,1.100000,6.460000,14.460,140779.191667,2,0.00,52.560,16.160,88.960
1148,1148,950300301,2.0,0.5,6.970,1.80,22.560000,103.560000,1.380000,2.940000,3.000,6779.931667,2,0.00,11.270,9.270,13.270
1149,1149,950300350,5.5,6.5,1.000,0.80,6.600000,27.550000,NaN,3.000000,1.000,11099.390000,2,0.00,13.800,4.200,23.400
1150,1150,950630012,0.0,0.0,11.300,2.50,23.070000,177.880000,39.070000,5.330000,12.700,20931.220000,3,2.49,13.800,13.800,13.800
1151,1151,950807982,33.0,38.5,1.300,3.00,61.000000,288.230000,1.130000,7.690000,6.000,177318.826667,2,0.00,75.800,18.600,133.000

In [360]:
VAR_EXPL_CAT_2 = VAR_EXPL_CAT.copy()

In [361]:
VAR_EXPL_CAT_2['Personnel médical salarié'] = VAR_EXPL_CAT['Médecins salariés'] + VAR_EXPL_CAT["Autres personnels médicaux salariés"]
VAR_EXPL_CAT_2['Personnel médical libéral'] = VAR_EXPL_CAT['Médecins libéraux'] + VAR_EXPL_CAT["Autres personnels médicaux libéraux"]

In [362]:
VAR_EXPL_CAT_2 = VAR_EXPL_CAT_2[['Numero_finess', 'Personnel médical salarié','Personnel médical libéral','stjr',
       'Personnels de direction et administratifs',
       'Personnels des services de soins', 'Personnels éducatifs et sociaux',
       'Personnels médico-techniques', 'Personnels techniques et ouvriers',
        'Internes']]
VAR_EXPL_CAT_2= VAR_EXPL_CAT_2.fillna(0)

In [363]:
VAR_EXPL_CAT_2

,Numero_finess,Personnel médical salarié,Personnel médical libéral,stjr,Personnels de direction et administratifs,Personnels des services de soins,Personnels éducatifs et sociaux,Personnels médico-techniques,Personnels techniques et ouvriers,Internes
0,010007300,0.000,7.5,2,2.250000,4.200000,0.000000,0.000000,0.000,0.00
1,010008407,32.820,0.0,1,21.196667,97.323333,0.846667,9.206667,26.440,0.00
2,010009132,1.865,0.0,1,4.175000,46.700000,1.065000,1.130000,13.465,0.00
3,010780054,147.130,5.5,1,118.605000,388.590000,4.930000,107.660000,112.630,195.09
4,010780062,29.550,0.0,1,58.450000,336.540000,5.450000,29.320000,57.570,6.45
...,...,...,...,...,...,...,...,...,...,...
1147,950300277,7.060,45.5,2,74.950000,246.990000,1.100000,6.460000,14.460,0.00
1148,950300301,8.770,2.5,2,22.560000,103.560000,1.380000,2.940000,3.000,0.00
1149,950300350,1.800,12.0,2,6.600000,27.550000,0.000000,3.000000,1.000,0.00
1150,950630012,13.800,0.0,3,23.070000,177.880000,39.070000,5.330000,12.700,2.49
1151,950807982,4.300,71.5,2,61.000000,288.230000,1.130000,7.690000,6.000,0.00

In [364]:
VAR_EXPL_CAT_2 = VAR_EXPL_CAT_2.apply(lambda x: np.log(x) if x.name in ['Personnel médical salarié','Personnel médical libéral',
       'Personnels de direction et administratifs',
       'Personnels des services de soins', 'Personnels éducatifs et sociaux',
       'Personnels médico-techniques', 'Personnels techniques et ouvriers',
        'Internes'] else x)

#On remplace les valeurs -infini apparues après l'application du log par la valeur -3 c'est-à-dire log(0.001)
from numpy import inf
VAR_EXPL_CAT_2 = VAR_EXPL_CAT_2.replace(-inf, -3)

VAR_EXPL_CAT_2

C:\Users\Vinciane\Anaconda3\lib\site-packages\pandas\core\arraylike.py:358: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

,Numero_finess,Personnel médical salarié,Personnel médical libéral,stjr,Personnels de direction et administratifs,Personnels des services de soins,Personnels éducatifs et sociaux,Personnels médico-techniques,Personnels techniques et ouvriers,Internes
0,010007300,-3.000000,2.014903,2,0.810930,1.435085,-3.000000,-3.000000,-3.000000,-3.000000
1,010008407,3.491038,-3.000000,1,3.053844,4.578039,-0.166448,2.219928,3.274878,-3.000000
2,010009132,0.623261,-3.000000,1,1.429114,3.843744,0.062975,0.122218,2.600094,-3.000000
3,010780054,4.991317,1.704748,1,4.775799,5.962525,1.595339,4.678978,4.724108,5.273461
4,010780062,3.386084,-3.000000,1,4.068172,5.818717,1.695616,3.378270,4.053002,1.864080
...,...,...,...,...,...,...,...,...,...,...
1147,950300277,1.954445,3.817712,2,4.316821,5.509348,0.095310,1.865629,2.671386,-3.000000
1148,950300301,2.171337,0.916291,2,3.116178,4.640151,0.322083,1.078410,1.098612,-3.000000
1149,950300350,0.587787,2.484907,2,1.887070,3.316003,-3.000000,1.098612,0.000000,-3.000000
1150,950630012,2.624669,-3.000000,3,3.138533,5.181109,3.665355,1.673351,2.541602,0.912283
1151,950807982,1.458615,4.269697,2,4.110874,5.663759,0.122218,2.039921,1.791759,-3.000000

In [365]:
VAR_CTRL.describe()

,Points_ISA,stjr,Capital_Lit_MCO,Capital_Bloc,Capital_imagerie,Capital_Examens_biologiques,Capital_telemed,SEJHC_MED,SEJHC_CHI,SEJHC_OBS,SEJHC_MCO,Taux_chomage_par_dep,Population,Dep Moyenne Salaires Horaires,Dep Moyenne Salaires Cadre Horaires,Dep Moyenne Salaires Prof Intermédiaire Horaires,Dep Moyenne Salaires Employé Horaires,Moyenne Revenus Fiscaux Départementaux
count,1160.000000,1160.000000,1137.000000,1150.000000,1160.000000,1147.000000,1160.000000,1160.000000,1160.000000,1159.000000,1160.000000,1160.000000,1160.000000,1160.000000,1160.000000,1160.000000,1160.000000,1160.000000
mean,11.353144,1.706897,4.226901,0.807590,-0.006461,1.250664,-1.976544,3952.631964,2094.817960,673.190511,6720.060098,8.291121,10.163531,11.795883,21.766274,12.675999,8.784310,10649.390517
std,1.753422,0.716106,1.418402,2.260586,2.280211,7.168320,1.715649,5174.050854,2472.139334,1147.577563,7604.160425,1.662088,1.667519,1.909655,1.674863,0.522909,0.353789,2065.446677
min,4.903718,1.000000,-3.000000,-3.000000,-3.000000,-3.000000,-3.000000,0.000000,0.000000,0.000000,0.000000,5.000000,5.204007,9.862500,19.750000,11.740000,8.261905,6282.000000
25%,10.307845,1.000000,3.555348,0.000000,-3.000000,-3.000000,-3.000000,366.250000,0.000000,0.000000,1205.500000,7.000000,8.994079,10.633333,20.775000,12.357075,8.555172,9471.000000
50%,11.529000,2.000000,4.442651,1.791759,1.098612,-3.000000,-3.000000,1963.000000,1430.500000,0.000000,4168.500000,8.000000,10.041291,11.204762,21.280808,12.535714,8.700862,10239.000000
75%,12.607883,2.000000,5.143611,2.374068,1.945910,10.922160,0.000000,5563.750000,3176.250000,1080.875000,9741.250000,9.300000,11.039284,11.981429,22.083750,12.902500,8.848113,11536.000000
max,16.025641,3.000000,6.961296,4.060443,3.332205,16.176472,2.397895,39884.000000,20991.000000,7639.000000,60719.000000,13.800000,14.569683,17.800000,27.600000,14.185000,9.742553,16895.000000

In [366]:
VAR_CTRL.columns

Index(['Numero_finess', 'Points_ISA', 'stjr', 'dep', 'Departement', 'COMINSEE',
       'Capital_Lit_MCO', 'Capital_Bloc', 'Capital_imagerie',
       'Capital_Examens_biologiques', 'Capital_telemed', 'SEJHC_MED',
       'SEJHC_CHI', 'SEJHC_OBS', 'SEJHC_MCO', 'Taux_chomage_par_dep',
       'Population', 'Dep Moyenne Salaires Horaires',
       'Dep Moyenne Salaires Cadre Horaires',
       'Dep Moyenne Salaires Prof Intermédiaire Horaires',
       'Dep Moyenne Salaires Employé Horaires',
       'Moyenne Revenus Fiscaux Départementaux', 'Bloc_politique'],
      dtype='object')

On garde les 25% d'hopitaux avec les salaires horaires des cadres les plus bas (<20.7750, et les 25% d'hopitaux avec les salaires horaires les plus élevés.(>22.083750)

In [367]:
# Les établissements avec des revenus départements  trés élevés

VAR_CTRL_ELEVES_2 = VAR_CTRL.copy()
VAR_CTRL_ELEVES_2= VAR_CTRL_ELEVES_2.rename(columns = {'Dep Moyenne Salaires Cadre Horaires': 'sal_cadre_moyen'})

VAR_CTRL_ELEVES_2= VAR_CTRL_ELEVES_2[VAR_CTRL_ELEVES_2.sal_cadre_moyen >= 22.083750]

In [368]:
# Les établissements avec des revenus départements trésfaibles

VAR_CTRL_FAIBLES_2 = VAR_CTRL.copy()
VAR_CTRL_FAIBLES_2 = VAR_CTRL_FAIBLES_2.rename(columns = {'Dep Moyenne Salaires Cadre Horaires': 'sal_cadre_moyen'})

VAR_CTRL_FAIBLES_2 = VAR_CTRL_FAIBLES_2[VAR_CTRL_FAIBLES_2.sal_cadre_moyen <= 20.7750]

In [369]:
VAR_CTRL_FAIBLES_2= VAR_CTRL_FAIBLES_2.fillna(0)
VAR_CTRL_ELEVES_2= VAR_CTRL_ELEVES_2.fillna(0)
#stjr_1 = stjr_1.fillna(0)

In [370]:
analyse_sal_faibles = pd.merge(VAR_CTRL_FAIBLES_2, VAR_EXPL_CAT_2)

analyse_sal_eleves = pd.merge(VAR_CTRL_ELEVES_2, VAR_EXPL_CAT_2)

In [374]:
analyse_sal_faibles_X =analyse_sal_faibles[["Personnel médical salarié",'Personnel médical libéral',"Internes",'Personnels de direction et administratifs',
       'Personnels des services de soins', 'Personnels éducatifs et sociaux',
       'Personnels médico-techniques', 'Personnels techniques et ouvriers', 
        'Capital_Lit_MCO', 'Capital_Bloc', 'Capital_imagerie', 'Population',
       'Capital_Examens_biologiques', 'Capital_telemed']]
analyse_sal_faibles_Y =analyse_sal_faibles[['Points_ISA']]
analyse_sal_eleves_X =analyse_sal_eleves[["Personnel médical salarié",'Personnel médical libéral',"Internes",'Personnels de direction et administratifs',
       'Personnels des services de soins', 'Personnels éducatifs et sociaux',
       'Personnels médico-techniques', 'Personnels techniques et ouvriers', 
       'Capital_Lit_MCO', 'Capital_Bloc', 'Capital_imagerie', 'Population',
       'Capital_Examens_biologiques', 'Capital_telemed']]
analyse_dep_eleves_Y =analyse_sal_eleves[['Points_ISA']]

In [375]:
analyse_sal_faibles_X = sm.add_constant(analyse_sal_faibles_X) # on ajoute une constante, sinon la régression se fait sans, par défaut
y = analyse_sal_faibles[['Personnel médical libéral']]

model_sal_faibles = sm.OLS(y, analyse_sal_faibles_X)
results_sal_faibles = model_sal_faibles.fit()
print(results_sal_faibles.summary())

                                OLS Regression Results
=====================================================================================
Dep. Variable:     Personnel médical libéral   R-squared:                       1.000
Model:                                   OLS   Adj. R-squared:                  1.000
Method:                        Least Squares   F-statistic:                 2.388e+29
Date:                       Thu, 13 May 2021   Prob (F-statistic):               0.00
Time:                               16:48:44   Log-Likelihood:                 8369.0
No. Observations:                        280   AIC:                        -1.671e+04
Df Residuals:                            265   BIC:                        -1.665e+04
Df Model:                                 14
Covariance Type:                   nonrobust
=============================================================================================================
                                                coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------------------------------
const                                     -3.775e-15   1.74e-14     -0.217      0.828    -3.8e-14    3.04e-14
Personnel médical salarié                 -7.772e-16   1.83e-15     -0.425      0.671   -4.38e-15    2.82e-15
Personnel médical libéral                     1.0000   8.35e-16    1.2e+15      0.000       1.000       1.000
Internes                                  -8.396e-16   9.75e-16     -0.861      0.390   -2.76e-15    1.08e-15
Personnels de direction et administratifs   1.11e-15   3.55e-15      0.313      0.754   -5.87e-15    8.09e-15
Personnels des services de soins           6.106e-16   4.13e-15      0.148      0.882   -7.51e-15    8.74e-15
Personnels éducatifs et sociaux            -7.91e-16    1.7e-15     -0.464      0.643   -4.14e-15    2.56e-15
Personnels médico-techniques              -3.053e-16   1.38e-15     -0.221      0.825   -3.02e-15    2.41e-15
Personnels techniques et ouvriers         -2.082e-17   1.58e-15     -0.013      0.989   -3.12e-15    3.08e-15
Capital_Lit_MCO                            5.204e-16   2.63e-15      0.198      0.843   -4.66e-15     5.7e-15
Capital_Bloc                              -2.984e-16   1.25e-15     -0.238      0.812   -2.77e-15    2.17e-15
Capital_imagerie                          -1.631e-16   9.77e-16     -0.167      0.868   -2.09e-15    1.76e-15
Population                                 1.193e-15    1.5e-15      0.797      0.426   -1.75e-15    4.14e-15
Capital_Examens_biologiques               -2.755e-15   3.43e-16     -8.041      0.000   -3.43e-15   -2.08e-15
Capital_telemed                           -1.735e-17   9.97e-16     -0.017      0.986   -1.98e-15    1.95e-15
==============================================================================
Omnibus:                       81.594   Durbin-Watson:                   1.673
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               52.042
Skew:                           0.932   Prob(JB):                     5.00e-12
Kurtosis:                       2.006   Cond. No.                         155.
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [376]:
analyse_dep_eleves_X = sm.add_constant(analyse_dep_eleves_X) # on ajoute une constante, sinon la régression se fait sans, par défaut
y = analyse_dep_eleves[['Points_ISA']]

model_dep_eleves = sm.OLS(y, analyse_dep_eleves_X)
results_dep_eleves = model_dep_eleves.fit()
print(results_dep_eleves.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:             Points_ISA   R-squared:                       0.852
Model:                            OLS   Adj. R-squared:                  0.845
Method:                 Least Squares   F-statistic:                     120.7
Date:                Thu, 13 May 2021   Prob (F-statistic):          6.09e-105
Time:                        16:48:44   Log-Likelihood:                -283.16
No. Observations:                 287   AIC:                             594.3
Df Residuals:                     273   BIC:                             645.6
Df Model:                          13
Covariance Type:            nonrobust
=============================================================================================================
                                                coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------------------------------
const                                         9.7501      0.358     27.201      0.000       9.044      10.456
Personnel médical                             0.0318      0.048      0.666      0.506      -0.062       0.126
Internes                                      0.0753      0.020      3.721      0.000       0.035       0.115
Personnels de direction et administratifs    -0.0114      0.081     -0.140      0.889      -0.171       0.148
Personnels des services de soins              0.1348      0.091      1.484      0.139      -0.044       0.314
Personnels éducatifs et sociaux              -0.0406      0.033     -1.227      0.221      -0.106       0.025
Personnels médico-techniques                  0.0957      0.036      2.627      0.009       0.024       0.167
Personnels techniques et ouvriers             0.0162      0.052      0.312      0.755      -0.086       0.118
Capital_Lit_MCO                               0.2619      0.052      5.045      0.000       0.160       0.364
Capital_Bloc                                  0.3032      0.029     10.519      0.000       0.246       0.360
Capital_imagerie                              0.0742      0.023      3.235      0.001       0.029       0.119
Population                                   -0.0564      0.022     -2.609      0.010      -0.099      -0.014
Capital_Examens_biologiques                   0.0281      0.009      3.296      0.001       0.011       0.045
Capital_telemed                               0.0715      0.027      2.681      0.008       0.019       0.124
==============================================================================
Omnibus:                       25.142   Durbin-Watson:                   2.008
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               63.887
Skew:                           0.377   Prob(JB):                     1.34e-14
Kurtosis:                       5.185   Cond. No.                         135.
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.